authentication/urls.py
from django.urls import path, include
from . import views

app_name = "authentication"

urlpatterns = [
    path('login', views.login_user, name="login_user"),
    path('logout', views.logout_user, name="logout_user"),
    path('register', views.register, name="register"),
]

base/urls.py
from django.urls import path, include
from . import views

app_name = "base"

urlpatterns = [
    path('', views.base, name="base"),
    path('add-to-cart', views.add_to_cart, name="add_to_cart"),
    path('dashboard', views.dashboard, name="dashboard"),
]

hack_404/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('base.urls')),
    path('', include('product.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include
from . import views

app_name = "product"

urlpatterns = [
    path('shop', views.shop, name="shop"),
    path('add-to-cart', views.add_to_cart, name="add-to-cart"),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name="product-detail"),
    path('product-add', views.product_add, name="product-add"),
]

base/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name 


class Product(models.Model):
    user = models.ForeignKey(User, related_name="product", on_delete = models.CASCADE)
    name = models.CharField(max_length= 20)
    slug = models.SlugField()
    item_type = models.ForeignKey(Category,related_name="Product", on_delete=models.PROTECT)
    image = models.ImageField(upload_to="product/media")
    price = models.FloatField()
    description = models.TextField(max_length=200)
    is_custom = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.name 

    def get_absolute_url(self):
        return f"/product/{self.slug}"

class Cart(models.Model):
    product_name = models.CharField(max_length=256)
    quantity = models.IntegerField()
    price = models.FloatField()

    def __str__(self):
        return self.product_name

user/models.py
from django.db import models
from django.core.validators import MaxLengthValidator, MinLengthValidator


CITY = [
    ("KATHMANDU", "Kathmandu"),
    ("BHAKTAPUR", "Bhaktapur"),
    ("LALITPUR", "Lalitpur")
]

PROVINCE = [
    ('1','Province 1'),
    ('2', 'Province 2'),
    ('3', 'Bagmati'),
    ('4', 'Gandaki'),
    ('5','Province 5'),
    ('6', 'Karnali'),
    ('7', 'Sudurpaschim'),
]
class Seller(models.Model):
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='user/seller')
    contact = models.IntegerField(validators=[MaxLengthValidator(10), MinLengthValidator(10)])
    street_address1 = models.CharField(max_length=256)
    street_address2 = models.CharField(max_length=256)
    city = models.CharField(choices=CITY, max_length=256)
    province = models.CharField(choices=PROVINCE, max_length=15)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    



    

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

product/forms.py
from django import forms
from .models import Cart, Product

class CartForm(forms.ModelForm):
    class Meta:
        model = Cart 
        fields = ['product_name', 'quantity', 'price']


class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "slug",
            "item_type",
            "image",
            "price",
            "description",
        ]

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, UserRegisterForm

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/dashboard')
            else:
                return render(request, 'login.html', {'message':'You are not active user'})
        else:
            return render(request, 'login.html', {'message':'Invalid Login Credentials'})

    return render(request, 'login.html') 


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'login.html', context)


def register(request):
    if request.method=="POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect('/')
    else:
        form = UserRegisterForm()

    return render(request, 'register.html', {'form':form})

base/views.py
from django.shortcuts import render
from product.models import Product
from user.models import Seller
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def base(request):
    products = Product.objects.all()
    return render(request, 'base.html', {'products':products})

def dashboard(request, id):
    users = Seller.objects.all()
    user_id = Seller.objects.get(id=id)
    return render(request, 'dashboard/index.html', {'users':users, 'user_id':user_id})

def add_to_cart(request):
    if request.method== "POST":
        item_name = request.POST.get("item_name")
        quantity = request.POST.get("quantity")
        price = request.POST.get("price")
        print(item_name)
        c = Cart(product_name = item_name, quantity=quantity, price=price)
        c.save()

    return render(request, 'base.html')

@login_required()
def dashboard(request):
    products = Product.objects.filter(user=request.user)
    return render(request, 'dashboard/index.html', {'product_length':len(products)})

product/views.py
from django.shortcuts import render, redirect
from .models import Cart
from .forms import CartForm, ProductAddForm
from product.models import Product, Category
from django.views.generic.detail import DetailView

def add_to_cart(request):
    form = CartForm()
    return render(request, 'base.html', {'form':form})


def shop(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, 'shop.html', {'products':products, 'categories':categories})

class ProductDetailView(DetailView):
    model = Product
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context

def product_add(request):
    print('Worked')
    if request.method == "POST":
        form = ProductAddForm(request.POST)
        if form.is_valid():
            form.save(user=request.user)
            return redire('/product-add')

    else:
        form = ProductAddForm()
    return render(request, 'dashboard/add_product.html', {'form':form})

user/views.py
from django.shortcuts import render

# Create your views here.

authentication/templates/login.html
{% extends 'base.html' %}	
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<meta http-equiv="Refresh" content="0; url=/" />
{% else %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if message %}
                        <p><strong>{{ message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'authentication:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="/register">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

authentication/templates/register.html
{% extends 'base.html' %}	
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<meta http-equiv="Refresh" content="0; url=/" />
{% else %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Sign Up</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'authentication:register'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit">Submit</button>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="/login">Click here</a> to login.
                </div>
            </div>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

base/templates/dashboard/add_product.html
  {% extends 'dashboard/index.html'%}
  {% load crispy_forms_tags %}
  {% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Your Product</h3>
              </div>
              {% if message %}
                {{message}}
              {% endif %}
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'product:product-add' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    {{form|crispy}}
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock %}
  

base/templates/dashboard/demo_1/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/ionicons/css/ionicons.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/typicons/src/font/typicons.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.addons.css'%}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/shared/style.css'%}">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/demo_1/style.css'%}">
    <!-- End Layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png'%}" />
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
          <a class="navbar-brand brand-logo" href="dashboard">
            <img src="#" alt="logo" /> </a>
          <a class="navbar-brand brand-logo-mini" href="dashboard">
            <img src="#" alt="logo" /> </a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center">
          <ul class="navbar-nav">
            <li class="nav-item font-weight-semibold d-none d-lg-block">Help : +050 2992 709</li>
            <li class="nav-item dropdown language-dropdown">
              <a class="nav-link dropdown-toggle px-2 d-flex align-items-center" id="LanguageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <div class="d-inline-flex mr-0 mr-md-3">
                  <div class="flag-icon-holder">
                    <i class="flag-icon flag-icon-us"></i>
                  </div>
                </div>
                <span class="profile-text font-weight-medium d-none d-md-block">English</span>
              </a>
              <div class="dropdown-menu dropdown-menu-left navbar-dropdown py-2" aria-labelledby="LanguageDropdown">
                <a class="dropdown-item">
                  <div class="flag-icon-holder">
                    <i class="flag-icon flag-icon-us"></i>
                  </div>English
                </a>
                <a class="dropdown-item">
                  <div class="flag-icon-holder">
                    <i class="flag-icon flag-icon-fr"></i>
                  </div>French
                </a>
                <a class="dropdown-item">
                  <div class="flag-icon-holder">
                    <i class="flag-icon flag-icon-ae"></i>
                  </div>Arabic
                </a>
                <a class="dropdown-item">
                  <div class="flag-icon-holder">
                    <i class="flag-icon flag-icon-ru"></i>
                  </div>Russian
                </a>
              </div>
            </li>
          </ul>
          <form class="ml-auto search-form d-none d-md-block" action="#">
            <div class="form-group">
              <input type="search" class="form-control" placeholder="Search Here">
            </div>
          </form>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-bell-outline"></i>
                <span class="count">7</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
                <a class="dropdown-item py-3">
                  <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
                  <span class="badge badge-pill badge-primary float-right">View all</span>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="{% static 'assets/images/faces/face10.jpg' %}" alt="image" class="img-sm profile-pic"> </div>
                  <div class="preview-item-content flex-grow py-2">
                    <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                    <p class="font-weight-light small-text"> The meeting is cancelled </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="{% static 'assets/images/faces/face12.jpg' %}" alt="image" class="img-sm profile-pic"> </div>
                  <div class="preview-item-content flex-grow py-2">
                    <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                    <p class="font-weight-light small-text"> The meeting is cancelled </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="{% static 'assets/images/faces/face1.jpg' %}" alt="image" class="img-sm profile-pic"> </div>
                  <div class="preview-item-content flex-grow py-2">
                    <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                    <p class="font-weight-light small-text"> The meeting is cancelled </p>
                  </div>
                </a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="mdi mdi-email-outline"></i>
                <span class="count bg-success">3</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
                <a class="dropdown-item py-3 border-bottom">
                  <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
                  <span class="badge badge-pill badge-primary float-right">View all</span>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-alert m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
                    <p class="font-weight-light small-text mb-0"> Just now </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-settings m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
                    <p class="font-weight-light small-text mb-0"> Private message </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-airballoon m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
                    <p class="font-weight-light small-text mb-0"> 2 days ago </p>
                  </div>
                </a>
              </div>
            </li>
            <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
              <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face8.jpg'%}" alt="Profile image"> </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                <div class="dropdown-header text-center">
                  <img class="img-md rounded-circle" src="{% static 'assets/images/faces/face8.jpg' %}" alt="Profile image">
                  <p class="mb-1 mt-3 font-weight-semibold">Allen Moreno</p>
                  <p class="font-weight-light text-muted mb-0">Utsav Kuinkel</p>
                </div>
                <a class="dropdown-item">My Profile <span class="badge badge-pill badge-danger">1</span><i class="dropdown-item-icon ti-dashboard"></i></a>
                <a class="dropdown-item">Messages<i class="dropdown-item-icon ti-comment-alt"></i></a>
                <a class="dropdown-item">Activity<i class="dropdown-item-icon ti-location-arrow"></i></a>
                <a class="dropdown-item">FAQ<i class="dropdown-item-icon ti-help-alt"></i></a>
                <a class="dropdown-item">Sign Out<i class="dropdown-item-icon ti-power-off"></i></a>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-profile">
              <a href="#" class="nav-link">
                <div class="profile-image">
                  <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face8.jpg' %}" alt="profile image">
                  <div class="dot-indicator bg-success"></div>
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user}}</p>
                  <p class="designation">Premium user</p>
                </div>
              </a>
            </li>
            <li class="nav-item nav-category">Main Menu</li>
            <li class="nav-item">
              <a class="nav-link" href="dashboard">
                <i class="menu-icon typcn typcn-document-text"></i>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
          </ul>
        </nav>
        <!-- partial -->
        <!-- main-panel ends -->
        <h1>Working On!!!</h1>
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{%static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{%static 'assets/vendors/js/vendor.bundle.addons.js'%}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="{%static 'assets/js/shared/off-canvas.js' %}"></script>
    <script src="{%static 'assets/js/shared/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{%static 'assets/js/demo_1/dashboard.js' %}"></script>
    <!-- End custom js for this page-->
  </body>
</html>

base/templates/dashboard/demo_1/partials/_footer.html
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2019 <a href="http://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i>
    </span>
  </div>
</footer>

base/templates/dashboard/demo_1/partials/_sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <a href="#" class="nav-link">
        <div class="profile-image">
          <img class="img-xs rounded-circle" src="assets/images/faces/face8.jpg" alt="profile image">
          <div class="dot-indicator bg-success"></div>
        </div>
        <div class="text-wrapper">
          <p class="profile-name">Allen Moreno</p>
          <p class="designation">Premium user</p>
        </div>
      </a>
    </li>
    <li class="nav-item nav-category">Main Menu</li>
    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="menu-icon typcn typcn-document-text"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <i class="menu-icon typcn typcn-coffee"></i>
        <span class="menu-title">Basic UI Elements</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/ui-features/typography.html">Typography</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="pages/forms/basic_elements.html">
        <i class="menu-icon typcn typcn-shopping-bag"></i>
        <span class="menu-title">Form elements</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="pages/charts/chartjs.html">
        <i class="menu-icon typcn typcn-th-large-outline"></i>
        <span class="menu-title">Charts</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="pages/tables/basic-table.html">
        <i class="menu-icon typcn typcn-bell"></i>
        <span class="menu-title">Tables</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="pages/icons/font-awesome.html">
        <i class="menu-icon typcn typcn-user-outline"></i>
        <span class="menu-title">Icons</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
        <i class="menu-icon typcn typcn-document-add"></i>
        <span class="menu-title">User Pages</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="auth">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="pages/samples/blank-page.html"> Blank Page </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/samples/login.html"> Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/samples/register.html"> Register </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/samples/error-404.html"> 404 </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/samples/error-500.html"> 500 </a>
          </li>
        </ul>
      </div>
    </li>
  </ul>
</nav>